#if defined FORMATS_INCLUDED
#endinput
#endif
#define FORMATS_INCLUDED

#define STA_RootPath "data/Source Tool Assist"
#define STA_ReplayFolder "Replays"
#define STA_ZoneFolder "Zones"

#define STA_MessagePrefix "{vintage}[{dodgerblue}STA{vintage}]{ghostwhite} - "
#define STA_CSGOMessagePrefix "{lightblue}[{darkblue}STA{lightblue}]{default} - "

#define STA_CheckpointFormat "{ghostwhite}Checkpoint [{unique}%d{ghostwhite}] {lightblue}%s"
#define STA_CSGOCheckpointFormat "{default}Checkpoint [{orange}%d{default}] {bluegrey}%s"

#define STA_EndFinishFormat "{orchid}%s {ghostwhite}finished in {unique}%s"
#define STA_CSGOEndFinishFormat "{orchid}%s {default}finished in {orange}%s"

#define STA_ZoneSpeedEnterFormat "{ghostwhite}Zone enter velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
#define STA_CSGOZoneSpeedEnterFormat "{default}Zone enter velocity XY: {bluegrey}%0.2f{default} - Z: {bluegrey}%0.2f"

#define STA_ZoneSpeedLeaveFormat "{ghostwhite}Zone leave velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
#define STA_CSGOZoneSpeedLeaveFormat "{default}Zone leave velocity XY: {bluegrey}%0.2f{default} - Z: {bluegrey}%0.2f"
