#if defined FORMATS_INCLUDED
#endinput
#endif
#define FORMATS_INCLUDED

#include "Include\morecolors.inc"

#define STA_MessagePrefix "{vintage}[{dodgerblue}STA{vintage}]{ghostwhite} - "
#define STA_ReplayPath "Source Tool Assist\\Replays\\"
#define STA_ZonePath "Source Tool Assist\\Zones\\"

#define STA_CheckpointFormat "{ghostwhite}Checkpoint [{unique}%d{ghostwhite}] {lightblue}%s"
#define STA_EndFinishFormat "{orchid}%s {ghostwhite}finished in {unique}%s"

#define STA_ZoneSpeedLeaveFormat "{ghostwhite}Zone leave velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
#define STA_ZoneSpeedEnterFormat "{ghostwhite}Zone enter velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
