#if defined FORMATS_INCLUDED
#endinput
#endif
#define FORMATS_INCLUDED

#include "Include\morecolors.inc"
#define STA_RootPath "data/Source Tool Assist"
#define STA_ReplayFolder "Replays"
#define STA_ZoneFolder "Zones"

#define STA_MessagePrefix "{vintage}[{dodgerblue}STA{vintage}]{ghostwhite} - "

#define STA_CheckpointFormat "{ghostwhite}Checkpoint [{unique}%d{ghostwhite}] {lightblue}%s"
#define STA_EndFinishFormat "{orchid}%s {ghostwhite}finished in {unique}%s"

#define STA_ZoneSpeedLeaveFormat "{ghostwhite}Zone leave velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
#define STA_ZoneSpeedEnterFormat "{ghostwhite}Zone enter velocity XY: {lightblue}%0.2f{ghostwhite} - Z: {lightblue}%0.2f"
